baseURL = "/mickaper/"
languageCode = "en-us"
title = "[Names] Wedding"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/mickaper/"
    weight = 1
  [[menu.main]]
    name = "Details"
    url = "/details/"
    weight = 2 